### ISSUE TITLE
Add specification for if a path parameter is "major"

### ISSUE THREAD

**Issue by apacheli** [discord/discord-api-spec#28] opened 2023-09-13 02:23 UTC
As written in https://discord.com/developers/docs/topics/rate-limits#rate-limits

**Comment by danny-may** [comment] 2023-09-13 07:43
I think this is pretty similar to what i was asking for in #23

**Comment by mbialecka** [comment] 2023-09-14 12:47
This is a duplicate of #23

**Closed by mbialecka** 2023-09-14 12:47 UTC
